#!/bin/bash
case $(echo $DOCKER_TAG | awk -F- '{print $1}') in
    debian|ubuntu)
        docker build --build-arg BASE_IMAGE=$(echo $DOCKER_TAG | sed -e 's/\(^[^-]*\)-/\1:/') --build-arg WORD=$DOCKER_TAG -f $DOCKERFILE_PATH -t $IMAGE_NAME .
        ;;
    *)
        docker build --build-arg WORD=$DOCKER_TAG -f $DOCKERFILE_PATH -t $IMAGE_NAME .
        ;;
esac

